# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


require 'yaml'
require 'fileutils'
require 'uri'
require 'erb'

FILES_PATH = "./files/"
#SCRIPTS_PATH = "./mysql/scripts/"
JDK_FILE = "jdk-8u144-windows-x64.exe"
MYSQL_CONNECTOR = "mysql-connector-java-5.1.47.jar"
WINDOWS_DEFAULT_MOUNT = "C:\\Users\\vagrant\\"
MYSQL_DEFAULT_MOUNT = "/home/vagrant/"

CONFIGURATIONS = YAML.load_file('config.yaml')



Vagrant.configure(2) do |config|
  CONFIGURATIONS['boxes'].each do |box|
    config.vm.define box['output_box'] do |server_config|
      server_config.vm.box = box['base_box']
      server_config.vm.host_name = box['output_box']

      memory = 2048
      cpu = 1

        server_config.vm.provider :virtualbox do |vb|
          vb.gui = false
          vb.customize ['modifyvm', :id, '--memory', memory]
          vb.customize ['modifyvm', :id, '--cpus', cpu]
        end

        server_config.vm.network "private_network", ip: box['ip']

        if box['communicator']
          server_config.vm.communicator = "winrm"
        else
          server_config.vm.communicator = "ssh"
        end

        if box['ports']
          box['ports'].each do |port|
            server_config.vm.network "forwarded_port", guest: port, host: port, guest_ip: box['ip']
          end
        end

        if box['resources_windows']
          server_config.vm.provision "file", source: FILES_PATH + JDK_FILE, destination: WINDOWS_DEFAULT_MOUNT +
          JDK_FILE
          server_config.vm.provision "file", source: FILES_PATH + MYSQL_CONNECTOR, destination: WINDOWS_DEFAULT_MOUNT +
          MYSQL_CONNECTOR
          box['resources_windows'].each do |resource|
            source = FILES_PATH + resource
            server_config.vm.provision "file", source: source, destination: WINDOWS_DEFAULT_MOUNT + resource
          end
        end

        if box['resources_mysql']
           #server_config.vm.provision "file", source: SCRIPTS_PATH , destination: MYSQL_DEFAULT_MOUNT
           box['resources_mysql'].each do |resource|
             source = resource
             server_config.vm.provision "file", source: source, destination: MYSQL_DEFAULT_MOUNT
           end
        end

        if box['tools']
          Arg_1 = box['tools'][0]['git_version']
          Arg_2 = box['tools'][1]['python_version']
          Arg_3 = box['tools'][2]['nodejs_version']
          Arg_4 = box['tools'][3]['maven_version']
          server_config.vm.provision "shell", path: box["provisioner_script"], args: [JDK_FILE, Arg_1, Arg_2, Arg_3, Arg_4]
        else
          Arg = box["product"]
          server_config.vm.provision "shell", path: box["provisioner_script"], args: [Arg]
        end
    end
  end
end
